(phones | homophones) help: user.homophones_show_help()
phones <user.homophones_canonical>: user.homophones_show(homophones_canonical)
phones: user.homophones_show_selection()
force phones <user.homophones_canonical>: user.homophones_force_show(homophones_canonical)
force phones: user.homophones_force_show_selection()
